### ISSUE TITLE
Fix date not showing

### ISSUE THREAD

**Issue by ganesh-ic** [Identiticoders/android-super-gluu#1]
Date not showing by an error when parsing the date (wrong date format exception)

current format used: "yyyy-MM-dd'T'HH:mm:ss.SSSSSS"
change to: "yyyy-MM-dd'T'HH:mm:ssZ"

**Comment by tso-ic-sg** [comment]
@ganesh-ic to confirm, the default repo we forked will have this Date Format Exception error when building it?

**Comment by ganesh-ic** [comment]
> @ganesh-ic to confirm, the default repo we forked will have this Date Format Exception error when building it?

yes, correct
